INSERT INTO ADMIN.USERTABLE (USERID, ADRESS, CONTACTDETAILS, NAME, PASSWORD, ROLE, USERNAME, EMAIL, BIRTHDATE, SEX) VALUES (1, 'a', 'a', 'a', 'a', 'a', 'a', null, null, null)
INSERT INTO ADMIN.USERTABLE (USERID, ADRESS, CONTACTDETAILS, NAME, PASSWORD, ROLE, USERNAME, EMAIL, BIRTHDATE, SEX) VALUES (951, 'admin', 'admin', 'admin', 'admin', 'admin', 'admin', null, null, null)
INSERT INTO ADMIN.USERTABLE (USERID, ADRESS, CONTACTDETAILS, NAME, PASSWORD, ROLE, USERNAME, EMAIL, BIRTHDATE, SEX) VALUES (1301, 'a', 'a', 'a', 'a', 'student', 'a', null, null, null)
